[package]
name = "hpc-smith-waterman"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5"

# We include debug symbols in release builds for profiling
[profile.release]
opt-level = 3
lto = true
debug = true
