#!/bin/bash

set -e
cd "$(dirname $0)/.."

out_dir="zips"
out_zip="$out_dir/hpc-smith-waterman.zip"

echo "==> Zipping repo..."
mkdir -p $out_dir
rm -f "$out_zip"
zip -vr "$out_zip" bin/ scripts/ src/ .editorconfig .gitignore Cargo.lock Cargo.toml README.md

echo "==> Zipped to $out_zip"
